# Generated by Django 4.1 on 2022-08-28 14:08

from django.db import migrations, models
import django.db.models.deletion
import ed_bgs.models.Faction
from ed_bgs.models.Faction import default_faction


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ed_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_eddn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'faction',
                'verbose_name_plural': 'factions',
            },
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_eddn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('type', models.CharField(blank=True, choices=[('A', 'Anarchy'), ('C', 'Autocrati'), ('P', 'Corporazioni'), ('S', 'Social')], max_length=1, null=True, verbose_name='type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'government',
                'verbose_name_plural': 'governments',
            },
        ),
        migrations.CreateModel(
            name='MinorFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Minor Faction',
                'verbose_name_plural': 'Minor Factions',
            },
        ),
        migrations.CreateModel(
            name='MinorFactionInSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Influence', models.FloatField(blank=True, null=True, verbose_name='Influence')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Minor Faction in System',
                'verbose_name_plural': 'Minor Factions in Systems',
                'ordering': ('system', 'minorFaction'),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_eddn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.CharField(choices=[('H', 'Happiness'), ('E', 'Economy'), ('S', 'Security'), ('O', 'Other')], default='O', max_length=1, verbose_name='type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StateInMinorFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('R', 'Recovering'), ('A', 'Active'), ('P', 'Pending')], max_length=1)),
                ('minorFaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.minorfactioninsystem', verbose_name='Minor Faction')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.state', verbose_name='state')),
            ],
            options={
                'verbose_name': 'State from the Minor Faction',
                'verbose_name_plural': 'States from the Minor Factions',
                'ordering': ('minorFaction', 'state'),
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name', 'type'], name='ed_bgs_stat_name_826303_idx'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_state_name_type'),
        ),
        migrations.AddField(
            model_name='minorfactioninsystem',
            name='minorFaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.minorfaction', verbose_name='Minor Faction'),
        ),
        migrations.AddField(
            model_name='minorfactioninsystem',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_system.system', verbose_name='system'),
        ),
        migrations.AddField(
            model_name='minorfaction',
            name='allegiance',
            field=models.ForeignKey(default=default_faction, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.faction', verbose_name='allegiance'),
        ),
        migrations.AddField(
            model_name='minorfaction',
            name='government',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.government', verbose_name='government'),
        ),
        migrations.AddIndex(
            model_name='stateinminorfaction',
            index=models.Index(fields=['minorFaction', 'state', 'phase'], name='ed_bgs_stat_minorFa_2857a5_idx'),
        ),
        migrations.AddIndex(
            model_name='minorfactioninsystem',
            index=models.Index(fields=['system', 'minorFaction'], name='ed_bgs_mino_system__1009c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='minorfactioninsystem',
            constraint=models.UniqueConstraint(fields=('minorFaction', 'system'), name='unique_minosrs_faction_in_system'),
        ),
    ]
