# Generated by Django 4.1 on 2022-08-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('type', models.CharField(blank=True, choices=[('A', 'Anarchy'), ('C', 'Autocrati'), ('P', 'Corporazioni'), ('S', 'Social')], max_length=1, null=True, verbose_name='type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'government',
                'verbose_name_plural': 'governments',
            },
        ),
        migrations.AddField(
            model_name='minorfaction',
            name='allegiance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.faction', verbose_name='allegiance'),
            preserve_default=False,
        ),
    ]
