# Generated by Django 5.0 on 2024-07-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='powerinsystem',
            name='unique_power_in_system',
        ),
        migrations.RemoveIndex(
            model_name='powerinsystem',
            name='ed_bgs_powe_system__b03e72_idx',
        ),
    ]
