# Generated by Django 4.1 on 2022-09-11 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_system', '0004_alter_system_population'),
        ('ed_bgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('allegiance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.faction', verbose_name='allegiance')),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_system.system', verbose_name='headquarter')),
            ],
            options={
                'verbose_name': 'Power',
                'verbose_name_plural': 'Powers',
            },
        ),
    ]
