# Generated by Django 4.1 on 2022-09-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0002_power'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'ordering': ('name',), 'verbose_name': 'Power', 'verbose_name_plural': 'Powers'},
        ),
        migrations.AddIndex(
            model_name='power',
            index=models.Index(fields=['name', 'allegiance'], name='ed_bgs_powe_name_177e32_idx'),
        ),
        migrations.AddConstraint(
            model_name='power',
            constraint=models.UniqueConstraint(fields=('name', 'headquarter'), name='unique_power_name_and_headquarter'),
        ),
    ]
