# Generated by Django 4.1 on 2022-08-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0002_government_minorfaction_allegiance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minorfaction',
            options={'verbose_name': 'Minor Faction', 'verbose_name_plural': 'Minor Factions'},
        ),
        migrations.AddField(
            model_name='minorfaction',
            name='government',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.government', verbose_name='government'),
            preserve_default=False,
        ),
    ]
