# Generated by Django 4.1 on 2022-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0003_alter_power_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_eddn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'State of Power',
                'verbose_name_plural': 'States of Power',
                'ordering': ('name',),
            },
        ),
    ]
