# Generated by Django 4.1 on 2022-08-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0003_alter_minorfaction_options_minorfaction_government'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorfaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
