# Generated by Django 4.1 on 2022-09-17 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_system', '0004_alter_system_population'),
        ('ed_bgs', '0004_powerstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerInSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('powers', models.ManyToManyField(related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.power', verbose_name='Powers')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.powerstate', verbose_name='state')),
                ('system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_system.system', verbose_name='system')),
            ],
            options={
                'verbose_name': 'Power in System',
                'verbose_name_plural': 'Powers in Systems',
                'ordering': ('system',),
            },
        ),
        migrations.AddIndex(
            model_name='powerinsystem',
            index=models.Index(fields=['state'], name='ed_bgs_powe_state_i_500645_idx'),
        ),
    ]
