# Generated by Django 4.1 on 2022-08-22 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_system', '0006_alter_system_security'),
        ('ed_bgs', '0004_minorfaction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinorFactionInSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Influence', models.FloatField(blank=True, null=True, verbose_name='Influence')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Minor Faction in System',
                'verbose_name_plural': 'Minor Factions in Systems',
                'ordering': ('system', 'minorFaction'),
            },
        ),
        migrations.AddField(
            model_name='minorfaction',
            name='system',
            field=models.ManyToManyField(through='ed_bgs.MinorFactionInSystem', to='ed_system.system', verbose_name='system'),
        ),
        migrations.AddField(
            model_name='minorfactioninsystem',
            name='minorFaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.minorfaction', verbose_name='Minor Faction'),
        ),
        migrations.AddField(
            model_name='minorfactioninsystem',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_system.system', verbose_name='system'),
        ),
        migrations.AddIndex(
            model_name='minorfactioninsystem',
            index=models.Index(fields=['system', 'minorFaction'], name='ed_bgs_mino_system__1009c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='minorfactioninsystem',
            constraint=models.UniqueConstraint(fields=('minorFaction', 'system'), name='unique_minosrs_faction_in_system'),
        ),
    ]
