# Generated by Django 4.1 on 2022-08-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0005_minorfactioninsystem_minorfaction_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minorfaction',
            name='system',
        ),
    ]
