# Generated by Django 4.1 on 2022-08-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0007_faction__eddn'),
    ]

    operations = [
        migrations.AddField(
            model_name='government',
            name='_eddn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
