# Generated by Django 4.1 on 2022-08-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0008_government__eddn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorfaction',
            name='allegiance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.faction', verbose_name='allegiance'),
        ),
        migrations.AlterField(
            model_name='minorfaction',
            name='government',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.government', verbose_name='government'),
        ),
    ]
