# Generated by Django 4.1 on 2022-08-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_system', '0006_alter_system_security'),
        ('ed_bgs', '0009_alter_minorfaction_allegiance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorfactioninsystem',
            name='minorFaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.minorfaction', verbose_name='Minor Faction'),
        ),
        migrations.AlterField(
            model_name='minorfactioninsystem',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_system.system', verbose_name='system'),
        ),
    ]
