# Generated by Django 4.1 on 2022-08-26 17:18

from django.db import migrations, models
import django.db.models.deletion
from ed_bgs.models.Faction import default_faction


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0012_alter_state_name_state_unique_state_name_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorfaction',
            name='allegiance',
            field=models.ForeignKey(default=default_faction, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.faction', verbose_name='allegiance'),
        ),
    ]
