# Generated by Django 4.1 on 2022-08-26 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0013_alter_minorfaction_allegiance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateInMinorFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minorFaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.minorfactioninsystem', verbose_name='Minor Faction')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.state', verbose_name='state')),
            ],
            options={
                'verbose_name': 'State from the Minor Faction',
                'verbose_name_plural': 'States from the Minor Factions',
                'ordering': ('minorFaction', 'state'),
            },
        ),
        migrations.AddIndex(
            model_name='stateinminorfaction',
            index=models.Index(fields=['minorFaction', 'state'], name='ed_bgs_stat_minorFa_360b65_idx'),
        ),
    ]
