# Generated by Django 4.1 on 2022-08-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0014_stateinminorfaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='_eddn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
