# Generated by Django 4.1 on 2022-08-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='data')),
                ('schema', models.CharField(max_length=100, verbose_name='schema')),
                ('error', models.JSONField(blank=True, null=True, verbose_name='error')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='update')),
            ],
            options={
                'verbose_name': 'data log',
                'verbose_name_plural': 'data logs',
                'ordering': ['-update'],
            },
        ),
    ]
