# Generated by Django 4.1 on 2024-04-16 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eddn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='creat_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create at'),
            preserve_default=False,
        ),
    ]
