# Generated by Django 5.1.1 on 2025-02-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddn', '0002_alter_datalog_options_remove_datalog_creat_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalog',
            name='schema',
        ),
    ]
