# Generated by Django 5.1.1 on 2025-02-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddn', '0003_remove_datalog_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='count'),
        ),
    ]
