# Generated by Django 4.1 on 2023-02-04 15:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ed_body', '0022_ring_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_eddn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Sample type',
                'verbose_name_plural': 'Samples type',
            },
        ),
        migrations.CreateModel(
            name='SignalSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_eddn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Signal type',
                'verbose_name_plural': 'Signals type',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(help_text='number of Signals', validators=[django.core.validators.MinValueValidator(0, 'the count cannot be less than 0')], verbose_name='count')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_body.planet', verbose_name='planet')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_exploration.signalsignals', verbose_name='type')),
            ],
            options={
                'verbose_name': 'Signals',
                'verbose_name_plural': 'Signals',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_body.planet', verbose_name='planet')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_exploration.samplesignals', verbose_name='type')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
            },
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['type', 'planet'], name='ed_explorat_type_id_23ba63_idx'),
        ),
        migrations.AddConstraint(
            model_name='signal',
            constraint=models.UniqueConstraint(fields=('type', 'planet'), name='signal_unique_type_planet'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['type', 'planet'], name='ed_explorat_type_id_47ebce_idx'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('type', 'planet'), name='sample_unique_type_planet'),
        ),
    ]
