# Generated by Django 4.1 on 2022-09-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarLuminosity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'star luminosity',
                'verbose_name_plural': 'star luminosities',
            },
        ),
        migrations.CreateModel(
            name='StarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'star type',
                'verbose_name_plural': 'star types',
            },
        ),
    ]
