# Generated by Django 4.1 on 2022-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startype',
            name='_eddn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
