# Generated by Django 5.1.1 on 2024-12-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0002_alter_atmospherecomponent__eddn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebody',
            name='orbiting',
            field=models.GeneratedField(db_persist=True, expression=models.Q(('eccentricity__isnull', False), ('orbitalInclination__isnull', False), ('orbitalPeriod__isnull', False), ('periapsis__isnull', False), ('semiMajorAxis__isnull', False)), output_field=models.BooleanField(), verbose_name='orbiting'),
        ),
        migrations.AddField(
            model_name='basebody',
            name='rotating',
            field=models.GeneratedField(db_persist=True, expression=models.Q(('axialTilt__isnull', False), ('rotationPeriod__isnull', False)), output_field=models.BooleanField(), verbose_name='rotating'),
        ),
    ]
