# Generated by Django 5.1.1 on 2025-01-16 16:41

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0003_basebody_orbiting_basebody_rotating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atmospherecomponent',
            options={'ordering': ['name'], 'verbose_name': 'atmosphere component', 'verbose_name_plural': 'atmosphere components'},
        ),
        migrations.AlterModelOptions(
            name='atmospherecomponentinplanet',
            options={'ordering': ['pk'], 'verbose_name': 'atmosphere component in planet', 'verbose_name_plural': 'atmosphere components in planets'},
        ),
        migrations.AlterModelOptions(
            name='atmospheretype',
            options={'ordering': ['name'], 'verbose_name': 'atmosphere type', 'verbose_name_plural': 'atmosphere types'},
        ),
        migrations.AddField(
            model_name='atmospherecomponent',
            name='eddn',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce('_eddn', 'name'), output_field=models.CharField(), verbose_name='eddn'),
        ),
        migrations.AddField(
            model_name='atmospheretype',
            name='eddn',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce('_eddn', 'name'), output_field=models.CharField(), verbose_name='eddn'),
        ),
        migrations.AddField(
            model_name='startype',
            name='eddn',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce('_eddn', 'name'), output_field=models.CharField(), verbose_name='eddn'),
        ),
        migrations.AddField(
            model_name='volcanism',
            name='eddn',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce('_eddn', 'name'), output_field=models.CharField(), verbose_name='eddn'),
        ),
    ]
