# Generated by Django 4.1 on 2022-09-25 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0003_basebody_star_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebody',
            name='axialTilt',
            field=models.FloatField(blank=True, help_text='axial tilt of the body', null=True, validators=[django.core.validators.MinValueValidator(-360, 'the axial tilt cannot be less than -360'), django.core.validators.MaxValueValidator(360, 'the axial tilt cannot be greater than 360')], verbose_name='axial tilt'),
        ),
        migrations.AlterField(
            model_name='basebody',
            name='eccentricity',
            field=models.FloatField(blank=True, help_text='eccentricity of the orbit', null=True, validators=[django.core.validators.MinValueValidator(0, 'the eccentricity cannot be less than 0'), django.core.validators.MaxValueValidator(1, 'the eccentricity cannot be greater than 1')], verbose_name='eccentricity'),
        ),
        migrations.AlterField(
            model_name='basebody',
            name='orbitalInclination',
            field=models.FloatField(blank=True, help_text='orbital inclination of the body', null=True, validators=[django.core.validators.MinValueValidator(-360, 'the orbital inclination cannot be less than -360'), django.core.validators.MaxValueValidator(360, 'the orbital inclination cannot be greater than 360')], verbose_name='orbital inclination'),
        ),
        migrations.AlterField(
            model_name='basebody',
            name='orbitalPeriod',
            field=models.FloatField(blank=True, help_text='orbital period of the body in days', null=True, validators=[django.core.validators.MinValueValidator(0, 'the orbital period cannot be less than 0')], verbose_name='orbital period'),
        ),
        migrations.AlterField(
            model_name='basebody',
            name='periapsis',
            field=models.FloatField(blank=True, help_text='periapsis of the body', null=True, verbose_name='periapsis'),
        ),
        migrations.AlterField(
            model_name='basebody',
            name='rotationPeriod',
            field=models.FloatField(blank=True, help_text='rotation period of the body in seconds', null=True, validators=[django.core.validators.MinValueValidator(0, 'the rotation period cannot be less than 0')], verbose_name='rotation period'),
        ),
        migrations.AlterField(
            model_name='basebody',
            name='semiMajorAxis',
            field=models.FloatField(blank=True, help_text='semi major axis of the orbit', null=True, validators=[django.core.validators.MinValueValidator(0, 'the semi major axis cannot be less than 0')], verbose_name='semi major axis'),
        ),
    ]
