# Generated by Django 4.1 on 2022-09-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0004_alter_basebody_axialtilt_alter_basebody_eccentricity_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='star',
            index=models.Index(fields=['luminosity', 'starType'], name='luminosity_starType_idx'),
        ),
    ]
