# Generated by Django 4.1 on 2022-10-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0005_star_luminosity_startype_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebody',
            name='ascendingNode',
            field=models.FloatField(blank=True, help_text='ascending node of the orbit', null=True, verbose_name='ascending node'),
        ),
        migrations.AddField(
            model_name='basebody',
            name='meanAnomaly',
            field=models.FloatField(blank=True, help_text='mean anomaly of the orbit', null=True, verbose_name='mean anomaly'),
        ),
    ]
