# Generated by Django 5.1.1 on 2025-03-21 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0005_alter_atmospherecomponent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='absoluteMagnitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1, 'the absolute magnitude cannot be less than -1')], verbose_name='absolute magnitude'),
        ),
    ]
