# Generated by Django 4.1 on 2022-10-01 12:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0006_basebody_ascendingnode_basebody_meananomaly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('innerRad', models.FloatField(help_text='inner radius of the ring', validators=[django.core.validators.MinValueValidator(0, 'the inner radius cannot be less than 0')], verbose_name='inner radius')),
                ('outerRad', models.FloatField(help_text='outer radius of the ring', validators=[django.core.validators.MinValueValidator(0, 'the outer radius cannot be less than 0')], verbose_name='outer radius')),
                ('massMT', models.FloatField(help_text='mass of the ring', validators=[django.core.validators.MinValueValidator(0, 'the mass cannot be less than 0')], verbose_name='mass')),
                ('ringType', models.CharField(choices=[('MetalRich', 'Metal Rich'), ('Metallic', 'Metallic'), ('Rocky', 'Rocky'), ('Icy', 'Icy')], help_text='type of the ring', max_length=255, verbose_name='ring type')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_body.basebody', verbose_name='body')),
            ],
            options={
                'verbose_name': 'ring',
                'verbose_name_plural': 'rings',
            },
        ),
        migrations.AddIndex(
            model_name='ring',
            index=models.Index(fields=['body'], name='ed_body_rin_body_id_3298e2_idx'),
        ),
        migrations.AddIndex(
            model_name='ring',
            index=models.Index(fields=['ringType'], name='ed_body_rin_ringTyp_b36b49_idx'),
        ),
        migrations.AddConstraint(
            model_name='ring',
            constraint=models.UniqueConstraint(fields=('name', 'body'), name='unique_ring_name_body'),
        ),
        migrations.AddConstraint(
            model_name='ring',
            constraint=models.CheckConstraint(check=models.Q(('innerRad__lt', models.F('outerRad')), ('innerRad__isnull', True), ('outerRad__isnull', True), _connector='OR'), name='inner_radius_lt_outer_radius'),
        ),
    ]
