# Generated by Django 4.1 on 2022-10-04 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0007_ring_ring_ed_body_rin_body_id_3298e2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebody',
            name='radius',
            field=models.FloatField(blank=True, help_text='radius of the body', null=True, validators=[django.core.validators.MinValueValidator(0, 'the radius cannot be less than 0')], verbose_name='radius'),
        ),
        migrations.AlterField(
            model_name='basebody',
            name='surfaceTemperature',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'the surface temperature cannot be less than 0')], verbose_name='surface temperature'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='innerRad',
            field=models.FloatField(blank=True, help_text='inner radius of the ring', null=True, validators=[django.core.validators.MinValueValidator(0, 'the inner radius cannot be less than 0')], verbose_name='inner radius'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='massMT',
            field=models.FloatField(blank=True, help_text='mass of the ring', null=True, validators=[django.core.validators.MinValueValidator(0, 'the mass cannot be less than 0')], verbose_name='mass'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='outerRad',
            field=models.FloatField(blank=True, help_text='outer radius of the ring', null=True, validators=[django.core.validators.MinValueValidator(0, 'the outer radius cannot be less than 0')], verbose_name='outer radius'),
        ),
    ]
