# Generated by Django 4.1 on 2022-10-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0008_alter_basebody_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebody',
            name='rotationPeriod',
            field=models.FloatField(blank=True, help_text='rotation period of the body in seconds', null=True, verbose_name='rotation period'),
        ),
    ]
