# Generated by Django 4.1 on 2022-10-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0009_alter_basebody_rotationperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmosphereType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_eddn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'atmosphere type',
                'verbose_name_plural': 'atmosphere types',
            },
        ),
        migrations.AlterField(
            model_name='ring',
            name='ringType',
            field=models.CharField(choices=[('MetalRich', 'Metal Rich'), ('Metalic', 'Metalic'), ('Rocky', 'Rocky'), ('Icy', 'Icy')], help_text='type of the ring', max_length=255, verbose_name='ring type'),
        ),
    ]
