# Generated by Django 4.1 on 2022-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0012_atmospherecomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volcanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'volcanism',
                'verbose_name_plural': 'volcanisms',
            },
        ),
    ]
