# Generated by Django 4.1 on 2022-10-17 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0015_alter_planet_atmospheretype_alter_planet_landable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='_compositionIce',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0, 'the composition ice cannot be less than 0')], verbose_name='ice'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='_compositionMetal',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0, 'the composition metal cannot be less than 0')], verbose_name='metal'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='_compositionRock',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0, 'the composition rock cannot be less than 0')], verbose_name='rock'),
        ),
    ]
