# Generated by Django 4.1 on 2022-10-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0016_alter_planet__compositionice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='terraformState',
            field=models.CharField(blank=True, choices=[('Terraformable', 'Terraformable'), ('Terraforming', 'Terraforming'), ('Terraformed', 'Terraformed'), ('', 'Not Terraformable')], max_length=15, null=True, verbose_name='terraform state'),
        ),
    ]
