# Generated by Django 4.1 on 2022-10-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0017_alter_planet_terraformstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='volcanism',
            name='_eddn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
