# Generated by Django 4.1 on 2022-10-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0018_volcanism__eddn'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmospherecomponent',
            name='_eddn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
