# Generated by Django 4.1 on 2022-10-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0019_atmospherecomponent__eddn'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebody',
            name='parentsID',
            field=models.PositiveSmallIntegerField(default=0, help_text='enter the body ID of the object which orbit', verbose_name='parents ID'),
        ),
        migrations.AlterField(
            model_name='basebody',
            name='bodyID',
            field=models.PositiveIntegerField(verbose_name='body ID'),
        ),
    ]
