# Generated by Django 4.1 on 2022-11-12 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0020_basebody_parentsid_alter_basebody_bodyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebody',
            name='distance',
            field=models.FloatField(help_text='distance from the stary center', null=True, validators=[django.core.validators.MinValueValidator(0, 'the distance cannot be less than 0')], verbose_name='distance'),
        ),
        migrations.AlterField(
            model_name='basebody',
            name='parentsID',
            field=models.PositiveSmallIntegerField(default=0, help_text='enter the body ID of the object which orbit', null=True, verbose_name='parents ID'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='ringType',
            field=models.CharField(choices=[('MetalRich', 'Metal Rich'), ('Metalic', 'Metalic'), ('Rocky', 'Rocky'), ('Icy', 'Icy')], help_text='type of the ring', max_length=255, null=True, verbose_name='ring type'),
        ),
    ]
