# Generated by Django 4.1 on 2023-02-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0021_alter_basebody_distance_alter_basebody_parentsid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ring',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
