name: check and test
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build --file eddai_EliteDangerousApiInterface\Dockerfile -t eddaielitedangerousapiinterface:latest "eddai_EliteDangerousApiInterface" 
  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      db:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_DB: ed_info
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Run database flush
        run: docker run --rm \
        --network host \
        -e DJANGO_SECRET_KEY=on_5vt@hm3k#d*00&jy9sp%esjf$n#6%5fio$cu+(%tpji0@15 \
        -e DJANGO_SETTINGS_MODULE=eddai_EliteDangerousApiInterface.settings.test \
        -e POSTGIS_USER=test_user \
        -e POSTGIS_PASSWORD=test_password \
        eddaielitedangerousapiinterface:latest python manage.py flush --no-input
      - uses: actions/checkout@v4
      - name: Run database migrations
        run: docker run --rm \
        --network host \
        -e DJANGO_SECRET_KEY=on_5vt@hm3k#d*00&jy9sp%esjf$n#6%5fio$cu+(%tpji0@15 \
        -e DJANGO_SETTINGS_MODULE=eddai_EliteDangerousApiInterface.settings.test \
        -e POSTGIS_USER=test_user \
        -e POSTGIS_PASSWORD=test_password \
        eddaielitedangerousapiinterface:latest python manage.py migrate
      - name: Run tests
        run: docker run --rm \
        --network host \
        -e DJANGO_SECRET_KEY=on_5vt@hm3k#d*00&jy9sp%esjf$n#6%5fio$cu+(%tpji0@15 \
        -e DJANGO_SETTINGS_MODULE=eddai_EliteDangerousApiInterface.settings.test \
        -e POSTGIS_USER=test_user \
        -e POSTGIS_PASSWORD=test_password \
        eddaielitedangerousapiinterface:latest python manage.py test
