# Generated by Django 5.0 on 2024-05-30 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_eddn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True)),
                ('meanPrice', models.IntegerField(verbose_name='mean price')),
            ],
            options={
                'verbose_name': 'commodity',
                'verbose_name_plural': 'commodities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_eddn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'economy',
                'verbose_name_plural': 'economies',
            },
        ),
        migrations.CreateModel(
            name='CommodityInStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('buyPrice', models.IntegerField(default=0, help_text='the buy price of the commodity', verbose_name='buy price')),
                ('sellPrice', models.IntegerField(default=0, help_text='the sell price of the commodity', verbose_name='sell price')),
                ('inStock', models.IntegerField(default=0, help_text='the number of units in stock', verbose_name='stock')),
                ('stockBracket', models.IntegerField(default=0, help_text='the stock bracket of the commodity', verbose_name='stock bracket')),
                ('demand', models.FloatField(default=0, help_text='the demand of the commodity', verbose_name='demand')),
                ('demandBracket', models.IntegerField(default=0, help_text='the demand bracket of the commodity', verbose_name='demand bracket')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_economy.commodity', verbose_name='commodity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'commodity in station',
                'verbose_name_plural': 'commodities in station',
            },
        ),
    ]