# Generated by Django 4.1 on 2022-08-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_economy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='economy',
            name='_eddn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
