# Generated by Django 4.1 on 2023-04-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_station', '0005_alter_station_landingpad_and_more'),
        ('ed_economy', '0002_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='meanPrice',
            field=models.IntegerField(default=0, verbose_name='mean price'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommodityInStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyPrice', models.IntegerField(default=0, help_text='the buy price of the commodity', verbose_name='buy price')),
                ('sellPrice', models.IntegerField(default=0, help_text='the sell price of the commodity', verbose_name='sell price')),
                ('inStock', models.IntegerField(default=0, help_text='the number of units in stock', verbose_name='stock')),
                ('stockBracket', models.IntegerField(default=0, help_text='the stock bracket of the commodity', verbose_name='stock bracket')),
                ('demand', models.IntegerField(default=0, help_text='the demand of the commodity', verbose_name='demand')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_economy.commodity', verbose_name='commodity')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_station.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'commodity in station',
                'verbose_name_plural': 'commodities in station',
            },
        ),
        migrations.AddIndex(
            model_name='commodityinstation',
            index=models.Index(fields=['station'], name='ed_economy__station_5fb3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='commodityinstation',
            index=models.Index(fields=['commodity'], name='ed_economy__commodi_eb3c60_idx'),
        ),
        migrations.AddConstraint(
            model_name='commodityinstation',
            constraint=models.UniqueConstraint(fields=('station', 'commodity'), name='unique_commodity_in_station'),
        ),
    ]
