# Generated by Django 4.1 on 2023-04-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_economy', '0004_alter_commodityinstation_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityinstation',
            name='demandBracket',
            field=models.IntegerField(default=0, help_text='the demand bracket of the commodity', verbose_name='demand bracket'),
        ),
    ]
