# Generated by Django 5.1.1 on 2025-06-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed_economy', '0004_commodity_eddn_economy_eddn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodityinstation',
            options={'ordering': ['station', 'commodity__name'], 'verbose_name': 'commodity in station', 'verbose_name_plural': 'commodities in station'},
        ),
        migrations.AlterModelOptions(
            name='economy',
            options={'ordering': ['name'], 'verbose_name': 'economy', 'verbose_name_plural': 'economies'},
        ),
    ]
