# Generated by Django 4.1 on 2023-04-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed_economy', '0005_commodityinstation_demandbracket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'ordering': ['name'], 'verbose_name': 'commodity', 'verbose_name_plural': 'commodities'},
        ),
    ]
