# Generated by Django 4.1 on 2022-11-08 22:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_body', '0020_basebody_parentsid_alter_basebody_bodyid'),
        ('ed_mining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(help_text='number of HotSpot', validators=[django.core.validators.MinValueValidator(0, 'the count cannot be less than 0')], verbose_name='count')),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_body.ring', verbose_name='ring')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_mining.hotspotsignals', verbose_name='type')),
            ],
            options={
                'verbose_name': 'HotSpot',
                'verbose_name_plural': 'HotSpots',
            },
        ),
    ]
