# Generated by Django 4.1 on 2022-11-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_mining', '0002_hotspot'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hotspot',
            index=models.Index(fields=['type', 'ring'], name='ed_mining_h_type_id_4e53dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotspot',
            constraint=models.UniqueConstraint(fields=('type', 'ring'), name='unique_type_ring'),
        ),
    ]
