# Generated by Django 5.1.1 on 2025-06-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed_mining', '0003_hotspottype_eddn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotspot',
            options={'ordering': ['id'], 'verbose_name': 'HotSpot', 'verbose_name_plural': 'HotSpots'},
        ),
        migrations.AlterModelOptions(
            name='hotspottype',
            options={'ordering': ['name'], 'verbose_name': 'Hotspot Type', 'verbose_name_plural': 'Hotspot Type'},
        ),
        migrations.AlterModelOptions(
            name='ring',
            options={'ordering': ['id'], 'verbose_name': 'ring', 'verbose_name_plural': 'rings'},
        ),
    ]
