# Generated by Django 4.1 on 2023-02-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_mining', '0003_hotspot_ed_mining_h_type_id_4e53dd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
