# Generated by Django 4.1 on 2023-03-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_mining', '0004_hotspot_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_mining.hotspotsignals', verbose_name='type'),
        ),
    ]
