# Generated by Django 4.1 on 2023-09-08 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short Description For This Task', max_length=200, unique=True, verbose_name='Name')),
                ('task', models.CharField(help_text='The Name of the Celery Task that Should be Run.  (Example: "proj.tasks.import_contacts")', max_length=200, verbose_name='Task Name')),
                ('status', models.CharField(choices=[(None, '(Unknown)'), ('r', 'RUN'), ('s', 'STOP'), ('e', 'ERROR')], max_length=1)),
                ('args', models.TextField(blank=True, default='[]', help_text='JSON encoded positional arguments (Example: ["arg1", "arg2"])', verbose_name='Positional Arguments')),
                ('kwargs', models.TextField(blank=True, default='{}', help_text='JSON encoded keyword arguments (Example: {"argument": "value"})', verbose_name='Keyword Arguments')),
                ('routing_key', models.CharField(blank=True, default=None, help_text='Override Routing Key for low-level AMQP routing', max_length=200, null=True, verbose_name='Routing Key')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('st', 'START'), ('sp', 'STOP'), ('t', 'TRY'), ('e', 'ERROR')], max_length=2, verbose_name='event')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', related_query_name='event', to='django_service.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='status_index'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['routing_key'], name='routing_key_index'),
        ),
        migrations.AddIndex(
            model_name='serviceevent',
            index=models.Index(fields=['service'], name='service_id_index'),
        ),
        migrations.AddIndex(
            model_name='serviceevent',
            index=models.Index(fields=['event'], name='event_index'),
        ),
    ]
