# Generated by Django 4.1 on 2023-11-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceevent',
            options={'ordering': ['-created'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterField(
            model_name='service',
            name='args',
            field=models.JSONField(blank=True, default=[], help_text='JSON encoded positional arguments (Example: ["arg1", "arg2"])', verbose_name='Positional Arguments'),
        ),
        migrations.AlterField(
            model_name='service',
            name='kwargs',
            field=models.JSONField(blank=True, default={}, help_text='JSON encoded keyword arguments (Example: {"argument": "value"})', verbose_name='Keyword Arguments'),
        ),
        migrations.AlterField(
            model_name='service',
            name='task',
            field=models.CharField(help_text='The Name of the Celery Task that Should be Run.  (Example: "proj.tasks.import_contacts")', max_length=200, unique=True, verbose_name='Task Name'),
        ),
    ]
