# Generated by Django 4.1 on 2023-12-23 09:55

from django.db import migrations, models
import django_service.models.Service


class Migration(migrations.Migration):

    dependencies = [
        ('django_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='service',
            name='routing_key',
            field=models.CharField(blank=True, default=django_service.models.Service._routing_key_default, help_text='Override Routing Key for low-level AMQP routing', max_length=200, null=True, verbose_name='Routing Key'),
        ),
    ]
