# Generated by Django 4.1 on 2023-12-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_service', '0002_serviceevent_note_alter_service_routing_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceevent',
            old_name='note',
            new_name='meta',
        ),
    ]
