# Generated by Django 4.1 on 2023-03-29 21:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_system', '0004_alter_system_population'),
        ('ed_bgs', '0005_powerinsystem_and_more'),
        ('ed_economy', '0001_initial'),
        ('ed_station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('landingPad', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('N', 'None')], default='N', max_length=1, verbose_name='landing pad')),
                ('distance', models.FloatField(help_text='distance from the stary center', null=True, validators=[django.core.validators.MinValueValidator(0, 'the distance cannot be less than 0')], verbose_name='distance')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('minorFaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.minorfaction', verbose_name='Minor Faction')),
                ('primaryEconomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_%(app_label)s_%(class)s_related', related_query_name='primary_%(app_label)s_%(class)ss', to='ed_economy.economy', verbose_name='primary economy')),
                ('secondaryEconomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_%(app_label)s_%(class)s_related', related_query_name='secondary_%(app_label)s_%(class)ss', to='ed_economy.economy', verbose_name='secondary economy')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_system.system', verbose_name='system')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_station.stationtype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'station',
                'verbose_name_plural': 'stations',
            },
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['system'], name='ed_station__system__7a99c0_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['type'], name='ed_station__type_id_d2ba99_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['landingPad'], name='ed_station__landing_a8c723_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['primaryEconomy'], name='ed_station__primary_8a6a89_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['secondaryEconomy'], name='ed_station__seconda_8edfda_idx'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('name', 'system'), name='unique_station_in_system'),
        ),
    ]
