# Generated by Django 5.0 on 2024-10-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='_eddn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stationtype',
            name='_eddn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
