# Generated by Django 4.1 on 2023-03-29 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_station', '0002_station_station_ed_station__system__7a99c0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_station.service', verbose_name='service')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_station.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'service in station',
                'verbose_name_plural': 'services in station',
            },
        ),
        migrations.AddIndex(
            model_name='serviceinstation',
            index=models.Index(fields=['station'], name='station_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinstation',
            index=models.Index(fields=['service'], name='service_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceinstation',
            constraint=models.UniqueConstraint(fields=('station', 'service'), name='unique_service_in_station'),
        ),
    ]
