# Generated by Django 5.1.1 on 2025-06-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed_station', '0003_service_eddn_stationtype_eddn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceinstation',
            options={'ordering': ['station', 'service'], 'verbose_name': 'service in station', 'verbose_name_plural': 'services in station'},
        ),
        migrations.AlterModelOptions(
            name='stationtype',
            options={'ordering': ['name'], 'verbose_name': 'station type', 'verbose_name_plural': 'station types'},
        ),
    ]
