# Generated by Django 4.1 on 2023-03-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_station', '0003_serviceinstation_serviceinstation_station_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='service',
            field=models.ManyToManyField(through='ed_station.ServiceInStation', to='ed_station.service', verbose_name='service'),
        ),
    ]
