# Generated by Django 4.1 on 2023-03-31 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_economy', '0001_initial'),
        ('ed_station', '0004_station_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='landingPad',
            field=models.CharField(choices=[(None, 'None'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, null=True, verbose_name='landing pad'),
        ),
        migrations.AlterField(
            model_name='station',
            name='secondaryEconomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_%(app_label)s_%(class)s_related', related_query_name='secondary_%(app_label)s_%(class)ss', to='ed_economy.economy', verbose_name='secondary economy'),
        ),
    ]
