# Generated by Django 4.1 on 2023-04-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_economy', '0004_alter_commodityinstation_demand'),
        ('ed_station', '0005_alter_station_landingpad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='commodity',
            field=models.ManyToManyField(through='ed_economy.CommodityInStation', to='ed_economy.commodity', verbose_name='commodity'),
        ),
    ]
