# Generated by Django 4.1 on 2023-04-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed_station', '0006_station_commodity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
    ]
