# Generated by Django 4.1 on 2023-04-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0005_powerinsystem_and_more'),
        ('ed_station', '0007_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='minorFaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_bgs.minorfaction', verbose_name='Minor Faction'),
        ),
        migrations.AlterField(
            model_name='station',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_station.stationtype', verbose_name='type'),
        ),
    ]
