# Generated by Django 4.1 on 2023-05-28 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_economy', '0006_alter_commodity_options'),
        ('ed_station', '0008_alter_station_minorfaction_alter_station_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='primaryEconomy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_%(app_label)s_%(class)s_related', related_query_name='primary_%(app_label)s_%(class)ss', to='ed_economy.economy', verbose_name='primary economy'),
        ),
    ]
