upstream eddai_EliteDangerousApiInterface {
    server django:8080;
}

server {

    listen 80;

    location / {
        proxy_pass http://eddai_EliteDangerousApiInterface;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /app/static-server/;
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location /media/ {
        alias /app/media-server/;
        expires 7d;
        add_header Cache-Control "public";
    }

}