# Generated by Django 5.0 on 2024-08-01 12:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4979, unique=True, verbose_name='coordinate')),
                ('security', models.CharField(blank=True, choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('A', 'Anarchy')], max_length=1, null=True, verbose_name='security')),
                ('population', models.PositiveBigIntegerField(default=0, verbose_name='population')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems'
            },
        ),
    ]
