# Generated by Django 4.1 on 2022-08-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ed_economy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('x', models.FloatField(verbose_name='x coordinates')),
                ('y', models.FloatField(verbose_name='y coordinates')),
                ('z', models.FloatField(verbose_name='z coordinates')),
                ('security', models.CharField(blank=True, choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('A', 'Anarchy')], max_length=1, null=True, verbose_name='security')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='population')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('primaryEconomy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_primary_related', related_query_name='%(app_label)s_%(class)ss_primary', to='ed_economy.economy', verbose_name='economy')),
                ('secondaryEconomy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_secondary_related', related_query_name='%(app_label)s_%(class)ss_secondary', to='ed_economy.economy', verbose_name='economy')),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
            },
        ),
        migrations.AddConstraint(
            model_name='system',
            constraint=models.UniqueConstraint(fields=('x', 'y', 'z'), name='unique_system_coordinates'),
        ),
    ]
