# Generated by Django 4.1 on 2022-08-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='security',
            field=models.CharField(blank=True, choices=[('an', 'Anarchy'), ('hi', 'High'), ('lo', 'Low'), ('me', 'Medium')], max_length=2, null=True, verbose_name='security'),
        ),
    ]
