# Generated by Django 5.0 on 2024-05-30 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_bgs', '0001_initial'),
        ('ed_economy', '0002_initial'),
        ('ed_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': 'System', 'verbose_name_plural': 'Systems'},
        ),
        migrations.AddField(
            model_name='system',
            name='conrollingFaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_controlling_related', related_query_name='%(app_label)s_%(class)ss_controlling', to='ed_bgs.minorfaction', verbose_name='controlling faction'),
        ),
        migrations.AddField(
            model_name='system',
            name='primaryEconomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_primary_related', related_query_name='%(app_label)s_%(class)ss_primary', to='ed_economy.economy', verbose_name='Primary economy'),
        ),
        migrations.AddField(
            model_name='system',
            name='secondaryEconomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_secondary_related', related_query_name='%(app_label)s_%(class)ss_secondary', to='ed_economy.economy', verbose_name='Secondary economy'),
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['primaryEconomy', 'secondaryEconomy'], name='system_economy_idx'),
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['conrollingFaction'], name='system_controllingFaction_idx'),
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['security'], name='system_security_idx'),
        ),
        migrations.AddConstraint(
            model_name='system',
            constraint=models.UniqueConstraint(fields=('x', 'y', 'z'), name='unique_system_coordinates'),
        ),
    ]
