# Generated by Django 4.1 on 2022-09-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_economy', '0001_initial'),
        ('ed_bgs', '0001_initial'),
        ('ed_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='conrollingFaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_controlling_related', related_query_name='%(app_label)s_%(class)ss_controlling', to='ed_bgs.minorfaction', verbose_name='controlling faction'),
        ),
        migrations.AlterField(
            model_name='system',
            name='primaryEconomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_primary_related', related_query_name='%(app_label)s_%(class)ss_primary', to='ed_economy.economy', verbose_name='Primary economy'),
        ),
        migrations.AlterField(
            model_name='system',
            name='secondaryEconomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_secondary_related', related_query_name='%(app_label)s_%(class)ss_secondary', to='ed_economy.economy', verbose_name='Secondary economy'),
        ),
    ]
