# Generated by Django 4.1 on 2022-09-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_system', '0002_system_conrollingfaction_alter_system_primaryeconomy_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['primaryEconomy', 'secondaryEconomy'], name='system_economy_idx'),
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['conrollingFaction'], name='system_controllingFaction_idx'),
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['security'], name='system_security_idx'),
        ),
    ]
