# Generated by Django 4.1 on 2022-08-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_economy', '0001_initial'),
        ('ed_system', '0002_system_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='economy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_economy.economy', verbose_name='economy'),
        ),
        migrations.AddField(
            model_name='system',
            name='population',
            field=models.PositiveIntegerField(default=0, verbose_name='population'),
        ),
        migrations.AddField(
            model_name='system',
            name='secondaryEconomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_secondary_related', related_query_name='%(app_label)s_%(class)ss_secondary', to='ed_economy.economy', verbose_name='economy'),
        ),
        migrations.AlterField(
            model_name='system',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
