# Generated by Django 4.1 on 2022-09-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_system', '0003_system_system_economy_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='population',
            field=models.PositiveBigIntegerField(default=0, verbose_name='population'),
        ),
    ]
