# Generated by Django 4.1 on 2022-08-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed_system', '0003_system_economy_system_population_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='economy',
            new_name='primaryEconomy',
        ),
    ]
