# Generated by Django 4.1 on 2022-08-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed_economy', '0001_initial'),
        ('ed_system', '0004_rename_economy_system_primaryeconomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='primaryEconomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_primary_related', related_query_name='%(app_label)s_%(class)ss_primary', to='ed_economy.economy', verbose_name='economy'),
        ),
    ]
