# Generated by Django 4.1 on 2022-08-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_system', '0005_alter_system_primaryeconomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='security',
            field=models.CharField(blank=True, choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('A', 'Anarchy')], max_length=1, null=True, verbose_name='security'),
        ),
    ]
