name: Auto Deploy
on:
    push:
        branches:
            - main
env:
    HOST: ${{ secrets.PORTAINER_HOST }}
    PORTAINER_WEBHOOK_GUID: ${{ secrets.PORTAINER_WEBHOOK_GUID }}
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Portainer Webhook
              run: |
                  curl -X POST "https://${HOST}/api/stacks/webhooks/${PORTAINER_WEBHOOK_GUID}"
