name: dajgo-deploy
on:
  push:
    branches:
      - main
      - dev-branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start Deploy
        uses: timely-deploy/status-action@v1
        with:
          token: ${{ github.token }}
          state: "in_progress"
          deployment_id: ${{ github.event.deployment.id }}
      - name: Deploy
        uses: invi5H/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: ls
      - name: Mark deployment as success
        if: success()
        uses: timely-deploy/status-action@v1
        with:
          token: ${{ github.token }}
          state: "success"
          deployment_id: ${{ github.event.deployment.id }}
      - name: Mark deployment as failure
        if: failure()
        uses: timely-deploy/status-action@v1
        with:
          token: ${{ github.token }}
          state: "failure"
          deployment_id: ${{ github.event.deployment.id }}
