name: dajgo-deploy
on:
  push:
    branches:
      - main
      - dev-branch
jobs:
  deploy:
    name: dajgo-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: invi5H/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: ls
