name: dajgo-deploy
on:
  push:
    branches:
      - main
      - dev-branch
jobs:
  deploy:
    name: dajgo-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Start deployment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: ls
      - name: Mark deployment as success
        if: ${{ success() }}
      - name: Mark deployment as failed
        if: ${{ failure() }}
