# Generated by Django 5.0 on 2024-05-29 15:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ed_body', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_eddn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('type', models.CharField(choices=[('ma', 'manufactured'), ('ra', 'raw'), ('en', 'encoded')], max_length=2, verbose_name='type')),
                ('grade', models.IntegerField(choices=[(1, 'very common'), (2, 'common'), (3, 'standard'), (4, 'rare'), (5, 'very rare')], verbose_name='grade')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
                'indexes': [models.Index(fields=['type'], name='ed_material_type_e8fe20_idx'), models.Index(fields=['grade'], name='ed_material_grade_c45e75_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialInPlanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'the percent cannot be less than 0'), django.core.validators.MaxValueValidator(100, 'the percent cannot be greater than 100')], verbose_name='percent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_material.material', verbose_name='material')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='ed_body.planet', verbose_name='planet')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'material in planet',
                'verbose_name_plural': 'materials in planets',
                'indexes': [models.Index(fields=['planet', 'material'], name='planet_material_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='materialinplanet',
            constraint=models.UniqueConstraint(fields=('planet', 'material'), name='planet_material_uc'),
        ),
    ]
