# Generated by Django 4.1 on 2022-10-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_eddn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('type', models.CharField(choices=[('ma', 'manufactured'), ('ra', 'raw'), ('en', 'encoded')], max_length=2, verbose_name='type')),
                ('grade', models.IntegerField(choices=[(1, 'very common'), (2, 'common'), (3, 'standard'), (4, 'rare'), (5, 'very rare')], verbose_name='grade')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['type'], name='ed_material_type_e8fe20_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['grade'], name='ed_material_grade_c45e75_idx'),
        ),
    ]
